const quotes = [
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "If you're not embarrassed by the first version of your product, you've launched too late.", author: "Reid Hoffman" },
    { text: "The enemy of the best is not the worst. The enemy of the best is the good enough.", author: "James Clear" },
    { text: "Entrepreneurship is living a few years of your life like most people won't, so that you can spend the rest of your life like most people can't.", author: "Anonymous" },
    { text: "The biggest risk is not taking any risk.", author: "Peter Thiel" },
    { text: "You don't learn to walk by following rules. You learn by doing and falling over.", author: "Richard Branson" },
    { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
    { text: "Ideas are cheap. Execution is everything.", author: "Chris Sacca" },
    { text: "Vision without execution is hallucination.", author: "Thomas Edison" },
    { text: "It's hard to do a really good job on anything you don't think about in the shower.", author: "Paul Graham" },
    { text: "The best startups generally come from somebody needing to scratch an itch.", author: "Michael Arrington" },
    { text: "What gets measured gets managed.", author: "Peter Drucker" },
    { text: "Amateurs sit and wait for inspiration. The rest of us just get up and go to work.", author: "Stephen King" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Only the paranoid survive.", author: "Andy Grove" },
    { text: "The master has failed more times than the beginner has even tried.", author: "Stephen McCranie" },
    { text: "You have to see failure as the beginning and the middle, but never entertain it as an end.", author: "Jessica Herrin" },
    { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    { text: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt" },
    { text: "The obstacle is the way.", author: "Marcus Aurelius" },
    { text: "What would you attempt to do if you knew you could not fail?", author: "Robert Schuller" },
    { text: "Make something people want.", author: "Y Combinator" },
    { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" },
    { text: "People don't buy what you do; they buy why you do it.", author: "Simon Sinek" },
    { text: "The product that wins is the one that bridges customers to the future, not the one that requires a giant leap.", author: "Aaron Levie" },
    { text: "Be undeniably good. No marketing effort or social media buzzword can be a substitute for that.", author: "Anthony Volodkin" },
    { text: "Price is what you pay. Value is what you get.", author: "Warren Buffett" },
    { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
    { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
    { text: "The graveyard is the richest place on earth, because it is here that you will find all the hopes and dreams that were never fulfilled.", author: "Les Brown" },
    { text: "Argue for your limitations, and sure enough they're yours.", author: "Richard Bach" },
    { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
    { text: "Ships in harbor are safe, but that's not what ships are built for.", author: "John A. Shedd" },
    { text: "The cave you fear to enter holds the treasure you seek.", author: "Joseph Campbell" },
    { text: "You can't connect the dots looking forward; you can only connect them looking backwards.", author: "Steve Jobs" },
    { text: "The illiterate of the 21st century will not be those who cannot read and write, but those who cannot learn, unlearn, and relearn.", author: "Alvin Toffler" },
    { text: "In the beginner's mind there are many possibilities, but in the expert's there are few.", author: "Shunryu Suzuki" },
    { text: "Stay hungry. Stay foolish.", author: "Whole Earth Catalog" },
    { text: "If you're the smartest person in the room, you're in the wrong room.", author: "Unknown" },
    { text: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
    { text: "What got you here won't get you there.", author: "Marshall Goldsmith" },
    { text: "The main thing is to keep the main thing the main thing.", author: "Stephen Covey" },
    { text: "You can do anything, but not everything.", author: "David Allen" },
    { text: "Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.", author: "Zig Ziglar" },
    { text: "If everything is important, then nothing is.", author: "Patrick Lencioni" },
    { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln" },
    { text: "Create something today even if it sucks.", author: "Anonymous" },
    { text: "The best way to predict the future is to create it.", author: "Alan Kay" },
    { text: "If you don't build your dream, someone else will hire you to help them build theirs.", author: "Dhirubhai Ambani" },
    { text: "Competition is for losers.", author: "Peter Thiel" },
    { text: "Every moment in business happens only once. The next Bill Gates will not build an operating system. The next Larry Page won't make a search engine.", author: "Peter Thiel" },
    { text: "Brilliant thinking is rare, but courage is in even shorter supply than genius.", author: "Peter Thiel" },
    { text: "The most contrarian thing of all is not to oppose the crowd but to think for yourself.", author: "Peter Thiel" },
    { text: "Live life as if there is no luck.", author: "Paul Graham" },
    { text: "It's better to make a few people really happy than to make a lot of people semi-happy.", author: "Paul Graham" },
    { text: "The most dangerous thing is to keep your head down.", author: "Paul Graham" },
    { text: "If you want to do something that will change the world, build a software company. It's easier to make a billion dollars that way than any other way.", author: "Paul Graham" },
    { text: "You don't need a big company to build great things.", author: "Paul Graham" },
    { text: "Being too cautious is the biggest risk of all.", author: "Paul Graham" },
    { text: "The struggle with AI safety is that we're trying to build something smarter than us and make sure it stays on our side.", author: "Dario Amodei" },
    { text: "If you can be the person who creates something genuinely useful, the world tends to figure out how to reward you.", author: "Dario Amodei" },
    { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
    { text: "Failure is an option here. If things are not failing, you are not innovating enough.", author: "Elon Musk" },
    { text: "I think it's possible for ordinary people to choose to be extraordinary.", author: "Elon Musk" },
    { text: "Persistence is very important. You should not give up unless you are forced to give up.", author: "Elon Musk" },
    { text: "Some people don't like change, but you need to embrace change if the alternative is disaster.", author: "Elon Musk" },
    { text: "The first step is to establish that something is possible; then probability will occur.", author: "Elon Musk" },
    { text: "You want to be greedy when others are fearful. You want to be fearful when others are greedy.", author: "Sam Altman" },
    { text: "Great execution is at least ten times more important and a hundred times harder than a good idea.", author: "Sam Altman" },
    { text: "The hard part of running a business is that there are a hundred things that you could be doing, and only five of them matter.", author: "Sam Altman" },
    { text: "Long-term thinking is a competitive advantage because almost no one does it.", author: "Sam Altman" },
    { text: "In a lot of ways, it's not the money that allows you to do new things. It's the growth and the ability to find things that people want and to use your creativity to target those.", author: "Travis Kalanick" },
    { text: "Fear is the disease. Hustle is the antidote.", author: "Travis Kalanick" },

    // Naval Ravikant
    { text: "Forty hour workweeks are a relic of the Industrial Age. Knowledge workers function like athletes — train and sprint, then rest and reassess.", author: "Naval Ravikant" },
    { text: "A fit body, a calm mind, a house full of love. These things cannot be bought — they must be earned.", author: "Naval Ravikant" },
    { text: "Information is everywhere but its meaning is created by the observer that interprets it. Meaning is relative and there is no objective, over-arching meaning.", author: "Naval Ravikant" },
    { text: "If you're more passionate about founding a business than the business itself, you can fall into a ten year trap. Better to stay emotionally unattached and select the best opportunity that arises. Applies to relationships too.", author: "Naval Ravikant" },
    { text: "Smart money is just dumb money that's been through a crash.", author: "Naval Ravikant" },
    { text: "The secret to public speaking is to speak as if you were alone.", author: "Naval Ravikant" },
    { text: "Sophisticated foods are bittersweet (wine, beer, coffee, chocolate). Addictive relationships are cooperative and competitive. Work becomes flow at the limits of ability. The flavor of life is on the edge.", author: "Naval Ravikant" },
    { text: "Technology is not only the thing that moves the human race forward, but it's the only thing that ever has. Without technology, we're just monkeys playing in the dirt.", author: "Naval Ravikant" },
    { text: "The fundamental delusion — there is something out there that will make me happy and fulfilled forever.", author: "Naval Ravikant" },
    { text: "Success is the enemy of learning. It can deprive you of the time and the incentive to start over. Beginner's mind also needs beginner's time.", author: "Naval Ravikant" },
    { text: "Don't debate people in the media when you can debate them in the marketplace.", author: "Naval Ravikant" },
    { text: "A contrarian isn't one who always objects — that's a confirmist of a different sort. A contrarian reasons independently, from the ground up, and resists pressure to conform.", author: "Naval Ravikant" },
    { text: "The real struggle isn't proletariat vs bourgeois. It's between high-status elites and wealthy elites. When their cooperation breaks, revolution.", author: "Naval Ravikant" },
    { text: "Branding requires accountability. To build a great personal brand (an eponymous one), you must take on the risk of being publicly wrong.", author: "Naval Ravikant" },
    { text: "Before you can lie to another, you must first lie to yourself.", author: "Naval Ravikant" },
    { text: "Wealth creation is an evolutionarily recent positive-sum game. Status is an old zero-sum game. Those attacking wealth creation are often just seeking status.", author: "Naval Ravikant" },
    { text: "Even today, what to study and how to study it are more important than where to study it and for how long. The best teachers are on the Internet. The best books are on the Internet. The best peers are on the Internet. The tools for learning are abundant. It's the desire to learn that's scarce.", author: "Naval Ravikant" },
    { text: "This is such a short and precious life that it's really important that you don't spend it being unhappy.", author: "Naval Ravikant" },
    { text: "You make your own luck if you stay at it long enough.", author: "Naval Ravikant" },
    { text: "The power to make and break habits and learning how to do that is really important.", author: "Naval Ravikant" },
    { text: "Happiness is a choice and a skill and you can dedicate yourself to learning that skill and making that choice.", author: "Naval Ravikant" },
    { text: "We're not really here for that long and we don't really matter that much. And nothing that we do lasts. So eventually you will fade. Your works will fade. Your children will fade. Your thoughts will fade. This planet will fade. The sun will fade. It will all be gone.", author: "Naval Ravikant" },
    { text: "A rational person can find peace by cultivating indifference to things outside of their control.", author: "Naval Ravikant" },
    { text: "The first rule of handling conflict is don't hang around people who are constantly engaging in conflict.", author: "Naval Ravikant" },
    { text: "The problem happens when we have multiple desires. When we have fuzzy desires. When we want to do ten different things and we're not clear about which is the one we care about.", author: "Naval Ravikant" },
    { text: "People spend too much time doing and not enough time thinking about what they should be doing.", author: "Naval Ravikant" },
    { text: "The people who succeed are irrationally passionate about something.", author: "Naval Ravikant" },
    { text: "I don't plan. I'm not a planner. I prefer to live in the moment and be free and to flow and to be happy.", author: "Naval Ravikant" },
    { text: "If you see a get rich quick scheme, that's someone else trying to get rich off of you.", author: "Naval Ravikant" },
    { text: "If you try to micromanage yourself all you're going to do is make yourself miserable.", author: "Naval Ravikant" },
    { text: "Social media has degenerated into a deafening cacophony of groups signaling and repeating their shared myths.", author: "Naval Ravikant" },
    { text: "If it entertains you now but will bore you someday, it's a distraction. Keep looking.", author: "Naval Ravikant" },
    { text: "If the primary purpose of school was education, the Internet should obsolete it. But school is mainly about credentialing.", author: "Naval Ravikant" },
    { text: "Desire is a contract that you make with yourself to be unhappy until you get what you want.", author: "Naval Ravikant" },
    { text: "Technology is applied science. Science is the study of nature. Mathematics is the language of nature. Philosophy is the root of mathematics. All tightly interrelated.", author: "Naval Ravikant" },
    { text: "Be present above all else.", author: "Naval Ravikant" },
    { text: "All the benefits in life come from compound interest — money, relationships, habits — anything of importance.", author: "Naval Ravikant" },
    { text: "Who you do business with is just as important as what you choose to do.", author: "Naval Ravikant" },
    { text: "If you can't see yourself working with someone for life, don't work with them for a day.", author: "Naval Ravikant" },
    { text: "Earn with your mind, not your time.", author: "Naval Ravikant" },
    { text: "Humans are basically habit machines… I think learning how to break habits is actually a very important meta skill and can serve you in life almost better than anything else.", author: "Naval Ravikant" },
    { text: "The older the problem, the older the solution.", author: "Naval Ravikant" },
    { text: "It's the mark of a charlatan to try and explain simple things in complex ways and it's the mark of a genius to explain complicated things in simple ways.", author: "Naval Ravikant" },
    { text: "The Efficient Markets Hypothesis fails because humans are herd animals, not independent rational actors. Thus the best investors tend to be antisocial and contrarian.", author: "Naval Ravikant" },
    { text: "People who try to look smart by pointing out obvious exceptions actually signal the opposite.", author: "Naval Ravikant" },
    { text: "You're never going to get rich renting out your time.", author: "Naval Ravikant" },
    { text: "Lots of literacy in modern society, but not enough numeracy.", author: "Naval Ravikant" },
    { text: "Above 'product-market fit' is 'founder-product-market fit.'", author: "Naval Ravikant" },
    { text: "Society has had multiple stores of value, as none is perfectly secure. Gold, oil, dollars, real estate, (some) bonds & equities. Crypto is the first that's decentralized *and* digital.", author: "Naval Ravikant" },
    { text: "Crypto is a bet against the modern macroeconomic dogma, which is passed off as science, but is really a branch of politics — with rulers, winners, and losers.", author: "Naval Ravikant" },
    { text: "Clear thinkers appeal to their own authority.", author: "Naval Ravikant" },
    { text: "Think clearly from the ground up. Understand and explain from first principles. Ignore society and politics. Acknowledge what you have. Control your emotions.", author: "Naval Ravikant" },
    { text: "Cynicism is easy. Mimicry is easy. Optimistic contrarians are the rarest breed.", author: "Naval Ravikant" },
    { text: "If they can train you to do it, then eventually they will train a computer to do it.", author: "Naval Ravikant" },
    { text: "If you're desensitized to the fact that you're going to die, consider it a different way. As far as you're concerned, this world is going to end. Now what?", author: "Naval Ravikant" },
    { text: "Following your genuine intellectual curiosity is a better foundation for a career than following whatever is making money right now.", author: "Naval Ravikant" },
    { text: "Objectively, the world is improving. To the elites, it's falling apart as their long-lived institutions are flattened by the Internet.", author: "Naval Ravikant" },
    { text: "One of the most damaging and widespread social beliefs is the idea that most adults are incapable of learning new skills.", author: "Naval Ravikant" },
    { text: "A personal metric: how much of the day is spent doing things out of obligation rather than out of interest?", author: "Naval Ravikant" },
    { text: "Caught in a funk? Use meditation, music, and exercise to reset your mood. Then choose a new path to commit emotional energy for rest of day.", author: "Naval Ravikant" },
    { text: "To be honest, speak without identity.", author: "Naval Ravikant" },
    { text: "Politics is sports writ large — pick a side, rally the tribe, exchange stories confirming bias, hurl insults and threats at the other side.", author: "Naval Ravikant" },
    { text: "People who live far below their means enjoy a freedom that people busy upgrading their lifestyles can't fathom.", author: "Naval Ravikant" },
    { text: "We feel guilt when we no longer want to associate with old friends and colleagues who haven't changed. The price, and marker, of growth.", author: "Naval Ravikant" },
    { text: "The most important trick to be happy is to realize that happiness is a choice that you make and a skill that you develop. You choose to be happy, and then you work at it. It's just like building muscles.", author: "Naval Ravikant" },
    { text: "Don't do things that you know are morally wrong. Not because someone is watching, but because you are. Self-esteem is just the reputation that you have with yourself.", author: "Naval Ravikant" },
    { text: "Anger is a hot coal that you hold in your hand while waiting to throw it at someone else.", author: "Naval Ravikant" },
    { text: "All the real benefits of life come from compound interest.", author: "Naval Ravikant" },
    { text: "Total honesty at all times. It's almost always possible to be honest & positive.", author: "Naval Ravikant" },
    { text: "Truth is that which has predictive power.", author: "Naval Ravikant" },
    { text: "Watch every thought. Always ask, why am I having this thought?", author: "Naval Ravikant" },
    { text: "All greatness comes from suffering.", author: "Naval Ravikant" },
    { text: "Love is given, not received.", author: "Naval Ravikant" },
    { text: "Enlightenment is the space between your thoughts.", author: "Naval Ravikant" },
    { text: "Mathematics is the language of nature.", author: "Naval Ravikant" },
    { text: "Every moment has to be complete in and of itself.", author: "Naval Ravikant" },
    { text: "So I have no time for short-term things: dinners with people I won't see again, tedious ceremonies to please tedious people, traveling to places that I wouldn't go to on vacation.", author: "Naval Ravikant" },
    { text: "You can change it, you can accept it, or you can leave it. What is not a good option is to sit around wishing you would change it but not changing it, wishing you would leave it but not leaving it, and not accepting it. It's that struggle, that aversion, that is responsible for most of our misery. The phrase that I use the most to myself in my head is one word: accept.", author: "Naval Ravikant" },
    { text: "I don't have time is just saying it's not a priority.", author: "Naval Ravikant" },
    { text: "Happiness is a state where nothing is missing.", author: "Naval Ravikant" },
    { text: "If you don't love yourself who will?", author: "Naval Ravikant" },
    { text: "If being ethical were profitable everybody would do it.", author: "Naval Ravikant" },
    { text: "Someone who is using a lot of fancy words and big concepts probably doesn't know what they're talking about. The smartest people can explain things to a child; if you can't do that, you don't understand the concept.", author: "Naval Ravikant" },
    { text: "Escape competition through authenticity.", author: "Naval Ravikant" },
    { text: "Morality and ethics automatically emerge when we realize the long term consequences of our actions.", author: "Naval Ravikant" },
    { text: "School, politics, sports, and games train us to compete against others. True rewards — wealth, knowledge, love, fitness, and equanimity — come from ignoring others and improving ourselves.", author: "Naval Ravikant" },
    { text: "Signaling virtue is a vice.", author: "Naval Ravikant" },
    { text: "Investing favors the dispassionate. Markets efficiently separate emotional investors from their money.", author: "Naval Ravikant" },
    { text: "Reality is neutral. Our reactions reflect back and create our world. Judge, and feel separate and lonely. Anger, and lose peace of mind. Cling, and live in anxiety. Fantasize, and miss the present. Desire, and suffer until you have it. Heaven and hell are right here, right now.", author: "Naval Ravikant" },
    { text: "Knowledge is a skyscraper. You can take a shortcut with a fragile foundation of memorization, or build slowly upon a steel frame of understanding.", author: "Naval Ravikant" },
    { text: "A busy mind accelerates the perceived passage of time. Buy more time by cultivating peace of mind.", author: "Naval Ravikant" },
    { text: "Politics is the exercise of power without merit.", author: "Naval Ravikant" },
    { text: "Politics and merit are opposite ends of a spectrum. More political organizations are less productive, have less inequality, and top performers opt out. More merit based organizations have higher productivity, more inequality, and higher odds of internal fracture.", author: "Naval Ravikant" },
    { text: "Doctors won't make you healthy. Nutritionists won't make you slim. Teachers won't make you smart. Gurus won't make you calm. Mentors won't make you rich. Trainers won't make you fit. Ultimately, you have to take responsibility. Save yourself.", author: "Naval Ravikant" },
    { text: "You can have the mind or you can have the moment.", author: "Naval Ravikant" },
    { text: "You have to surrender, at least a little bit, to be the best version of yourself possible.", author: "Naval Ravikant" },
    { text: "Confucius had a great saying that every man has two lives, and the second starts when he realizes he has just one.", author: "Naval Ravikant" },
    { text: "There is no answer. The real answer is 'because.' You get to make up your own answer is the beauty. If there was a single answer, we would not be free. We would be trapped…we would all have to live to that answer…luckily there is no answer.", author: "Naval Ravikant" },
    { text: "Answers to all the great questions are paradoxes…How do I matter in this infinite universe? On the one hand, you're separate…every two points are infinitely different…life is a single player game…on the other hand…you're connected to everything, it's inseparable.", author: "Naval Ravikant" },
    { text: "The answer to that question, 'Do I matter?' is 'I am nothing, and I am everything'…all the great questions…all paradoxes…pursuing them is actually really useful because then it gives you certain intrinsic understanding in your life that brings a level of peace.", author: "Naval Ravikant" },
    { text: "You have to do hard things…to create your own meaning in life.", author: "Naval Ravikant" },
    { text: "The world just reflects your own feelings back at you. Reality is neutral.", author: "Naval Ravikant" },
    { text: "Let's go back to desire…this is old, old Buddhist wisdom…Desire to me is a contract that you make with yourself to be unhappy until you get what you want, and I keep that in front of mind…Pick your one overwhelming desire. It's okay to suffer over that one.", author: "Naval Ravikant" },
    { text: "The universe is rigged in such a way that if you just want one thing and you focus on that, you will get it. But everything else, you got to let go.", author: "Naval Ravikant" },
    { text: "Retirement is when you stop sacrificing today for some imaginary tomorrow. When today is complete, in and of itself, you're retired.", author: "Naval Ravikant" },
    { text: "The way to get out of the competition trap is actually to be authentic. The way to retire is actually to find the thing that you know how to do better than anybody. And, you know how to do that better than anybody because you love to do it.", author: "Naval Ravikant" },
    { text: "I'm always 'working.' It looks like work to them, but it feels like play to me.", author: "Naval Ravikant" },
    { text: "When you're actually trying to live your life in congruence with reality, you want to have a deep understanding of what you do and why you do it. So, it's much more important to know the basics really well than to know the advanced.", author: "Naval Ravikant" },
    { text: "Most of modern life, all our diseases, are diseases of abundance, not diseases of scarcity.", author: "Naval Ravikant" },
    { text: "The way to survive in modern society is to be an ascetic. It is to retreat from society. There's too much society everywhere you go…The only solution is turn it off.", author: "Naval Ravikant" },
    { text: "The ancient struggle used to be the tribal struggle…Modern life, we're so free, everything has become atomized, we stand alone…The modern struggle as an individual is…drawing your own boundaries, and there's no one there to help you.", author: "Naval Ravikant" },
    { text: "It's easier to change yourself than to change the world.", author: "Naval Ravikant" },
    { text: "Live the life you want other people to live.", author: "Naval Ravikant" },
    { text: "Life is really a single player game. It's all going on in your head. Whatever you think, you believe, will very much shape your reality. Both from what risks you take and what actions you perform, but also just everyday experiences of reality.", author: "Naval Ravikant" },
    { text: "Only the individual transcends.", author: "Naval Ravikant" },
    { text: "You want to rest your mind. You want to learn how to settle into your mind. Now, I look forward to solitary confinement. You leave me alone for a day, it will be the happiest day I've had in awhile. That is a superpower that I think everybody can attain.", author: "Naval Ravikant" },
    { text: "A clear mind, leads to better judgement, leads to better outcome.", author: "Naval Ravikant" },
    { text: "If you want to operate at peak performance, you have to learn how to tame your mind.", author: "Naval Ravikant" },
    { text: "If you want to be a clear thinker, you cannot pay attention to politics. It will destroy your ability to think.", author: "Naval Ravikant" },
    { text: "The mind should be a servant or tool, not the master…I want to break the habit of uncontrolled thinking.", author: "Naval Ravikant" },
    { text: "A busy mind can often rob you of peace of mind. The peace that we seek is not peace of mind, it's peace from mind.", author: "Naval Ravikant" },
    { text: "The way we think you get peace is by resolving all your external problems, but there are unlimited external problems. So, the only way to actually get peace is on the inside by giving up this idea of problems.", author: "Naval Ravikant" },
    { text: "If you understand things, if you see things properly, you will naturally, slowly develop peace from mind.", author: "Naval Ravikant" },
    { text: "You're born, you have a whole set of sensory experiences and stimulations and lights and colors and sounds, and then you die. And how you choose to interpret that is up to you. You do have that choice.", author: "Naval Ravikant" },
    { text: "You can meditate 24/7. Meditation is not a sit down, close your eyes activity. Meditation is just basically watching your own thoughts like you would watch anything else in the outside world.", author: "Naval Ravikant" },
    { text: "Peace is happiness at rest, and happiness is peace in motion. You can convert peace to happiness any time you want, but peace is want you want most of the time…If you're a peaceful person, anything you do will be a happy activity.", author: "Naval Ravikant" },
    { text: "Happiness is also a choice. If you're so smart, how come you aren't happy? How come you haven't figured that out? That's my challenge to all the people who think they're so smart and so capable.", author: "Naval Ravikant" },
    { text: "In every moment, in everything that happens, you can look on the bright side of something. So I used to do that forcibly and then I trained it until it became second nature.", author: "Naval Ravikant" },
    { text: "Most smart people over time realize that possessions don't make them happy. You have to go through that…As you get older, you just realize that there's no happiness in material possessions.", author: "Naval Ravikant" },
    { text: "Creativity is the last frontier…automation over a long enough period of time will replace every non-creative job…that's great news. That means that all of our basic needs are taken of, and what remains for us is to be creative, which is really what every human wants.", author: "Naval Ravikant" },
    { text: "Art is just creativity. It's just anything that's done for its own sake.", author: "Naval Ravikant" },
    { text: "Wisdom is understanding the long term consequences of your actions.", author: "Naval Ravikant" },
    { text: "I live for the aha moment…when you connect two things together that you hadn't connected together before…it helps form a steel framework of understanding in your mind that you can then hang other ideas off of…that's what I live for…it's like curiosity fulfilled.", author: "Naval Ravikant" },
    { text: "When you combine things you're not supposed to combine, people get interested.", author: "Naval Ravikant" },
    { text: "I like the model of life that the ancients had…there's sort of this arc to life where you try your hand at everything…You've got one life, just do everything you're gonna do.", author: "Naval Ravikant" },
    { text: "At some level, all humans are broad, we're all multivariate…at some deep level…every human, basically, is capable of every experience and every thought.", author: "Naval Ravikant" },
    { text: "Would I still be interested in learning this thing if I couldn't ever tell anybody about it? That's how I know it's real. That's how I know it's something I actually want to know.", author: "Naval Ravikant" },
    { text: "I no longer track books read or even care about books read. It's about understanding concepts.", author: "Naval Ravikant" },
    { text: "I probably read 1-2 hours a day, and that puts me in the top .00001%. I think that alone accounts for any material success that I've had in my life and any intelligence that I might have.", author: "Naval Ravikant" },
    { text: "When you look at the greatest artists and creators, they have this ability to start over that nobody else does.", author: "Naval Ravikant" },

    // Bruce Lee
    { text: "Be water, my friend.", author: "Bruce Lee" },
    { text: "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", author: "Bruce Lee" },
    { text: "Absorb what is useful, discard what is useless and add what is specifically your own.", author: "Bruce Lee" },
    { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
    { text: "Knowing is not enough, we must apply. Willing is not enough, we must do.", author: "Bruce Lee" },
    { text: "If you spend too much time thinking about a thing, you'll never get it done.", author: "Bruce Lee" },
    { text: "To hell with circumstances; I create opportunities.", author: "Bruce Lee" },
    { text: "Mistakes are always forgivable, if one has the courage to admit them.", author: "Bruce Lee" },
    { text: "A wise man can learn more from a foolish question than a fool can learn from a wise answer.", author: "Bruce Lee" },
    { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee" },
    { text: "The key to immortality is first living a life worth remembering.", author: "Bruce Lee" },
    { text: "If you always put limits on everything you do, it will spread into your work and into your life.", author: "Bruce Lee" },
    { text: "Adapt what is useful, reject what is useless, and add what is specifically your own.", author: "Bruce Lee" },
    { text: "Don't fear failure. Not failure, but low aim, is the crime.", author: "Bruce Lee" },
    { text: "Long-term consistency trumps short-term intensity.", author: "Bruce Lee" },
    { text: "It's not the daily increase but daily decrease. Hack away at the unessential.", author: "Bruce Lee" },
    { text: "Empty your cup so that it may be filled.", author: "Bruce Lee" },
    { text: "The more we value things, the less we value ourselves.", author: "Bruce Lee" },
    { text: "Real living is living for others.", author: "Bruce Lee" },
    { text: "As you think, so shall you become.", author: "Bruce Lee" },
    { text: "A goal is not always meant to be reached, it often serves simply as something to aim at.", author: "Bruce Lee" },
    { text: "Take things as they are. Punch when you have to punch. Kick when you have to kick.", author: "Bruce Lee" },
    { text: "In the middle of chaos lies opportunity.", author: "Bruce Lee" },
    { text: "The spirit of the individual is determined by his dominating thought habits.", author: "Bruce Lee" },
    { text: "Notice that the stiffest tree is most easily cracked, while the bamboo survives by bending with the wind.", author: "Bruce Lee" },
    { text: "Life itself is your teacher, and you are in a state of constant learning.", author: "Bruce Lee" },
    { text: "Use only that which works, and take it from any place you can find it.", author: "Bruce Lee" },
    { text: "Always be yourself, express yourself, have faith in yourself.", author: "Bruce Lee" },
    { text: "The possession of anything begins in the mind.", author: "Bruce Lee" }
];

// Get a random quote
const quote = quotes[Math.floor(Math.random() * quotes.length)];
document.getElementById('quote').textContent = '"' + quote.text + '"';
document.getElementById('author').textContent = '— ' + quote.author;

// Get blocked site from URL params
const params = new URLSearchParams(window.location.search);
const blockedSite = params.get('site') || 'Unknown site';
document.getElementById('siteName').textContent = blockedSite;
