const quotes = [
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "If you're not embarrassed by the first version of your product, you've launched too late.", author: "Reid Hoffman" },
    { text: "The enemy of the best is not the worst. The enemy of the best is the good enough.", author: "James Clear" },
    { text: "Entrepreneurship is living a few years of your life like most people won't, so that you can spend the rest of your life like most people can't.", author: "Anonymous" },
    { text: "The biggest risk is not taking any risk.", author: "Peter Thiel" },
    { text: "You don't learn to walk by following rules. You learn by doing and falling over.", author: "Richard Branson" },
    { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
    { text: "Ideas are cheap. Execution is everything.", author: "Chris Sacca" },
    { text: "Vision without execution is hallucination.", author: "Thomas Edison" },
    { text: "It's hard to do a really good job on anything you don't think about in the shower.", author: "Paul Graham" },
    { text: "The best startups generally come from somebody needing to scratch an itch.", author: "Michael Arrington" },
    { text: "What gets measured gets managed.", author: "Peter Drucker" },
    { text: "Amateurs sit and wait for inspiration. The rest of us just get up and go to work.", author: "Stephen King" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Only the paranoid survive.", author: "Andy Grove" },
    { text: "The master has failed more times than the beginner has even tried.", author: "Stephen McCranie" },
    { text: "You have to see failure as the beginning and the middle, but never entertain it as an end.", author: "Jessica Herrin" },
    { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    { text: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt" },
    { text: "The obstacle is the way.", author: "Marcus Aurelius" },
    { text: "What would you attempt to do if you knew you could not fail?", author: "Robert Schuller" },
    { text: "Make something people want.", author: "Y Combinator" },
    { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" },
    { text: "People don't buy what you do; they buy why you do it.", author: "Simon Sinek" },
    { text: "The product that wins is the one that bridges customers to the future, not the one that requires a giant leap.", author: "Aaron Levie" },
    { text: "Be undeniably good. No marketing effort or social media buzzword can be a substitute for that.", author: "Anthony Volodkin" },
    { text: "Price is what you pay. Value is what you get.", author: "Warren Buffett" },
    { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
    { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
    { text: "The graveyard is the richest place on earth, because it is here that you will find all the hopes and dreams that were never fulfilled.", author: "Les Brown" },
    { text: "Argue for your limitations, and sure enough they're yours.", author: "Richard Bach" },
    { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
    { text: "Ships in harbor are safe, but that's not what ships are built for.", author: "John A. Shedd" },
    { text: "The cave you fear to enter holds the treasure you seek.", author: "Joseph Campbell" },
    { text: "You can't connect the dots looking forward; you can only connect them looking backwards.", author: "Steve Jobs" },
    { text: "The illiterate of the 21st century will not be those who cannot read and write, but those who cannot learn, unlearn, and relearn.", author: "Alvin Toffler" },
    { text: "In the beginner's mind there are many possibilities, but in the expert's there are few.", author: "Shunryu Suzuki" },
    { text: "Stay hungry. Stay foolish.", author: "Whole Earth Catalog" },
    { text: "If you're the smartest person in the room, you're in the wrong room.", author: "Unknown" },
    { text: "Formal education will make you a living; self-education will make you a fortune.", author: "Jim Rohn" },
    { text: "What got you here won't get you there.", author: "Marshall Goldsmith" },
    { text: "The main thing is to keep the main thing the main thing.", author: "Stephen Covey" },
    { text: "You can do anything, but not everything.", author: "David Allen" },
    { text: "Lack of direction, not lack of time, is the problem. We all have twenty-four hour days.", author: "Zig Ziglar" },
    { text: "If everything is important, then nothing is.", author: "Patrick Lencioni" },
    { text: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln" },
    { text: "Create something today even if it sucks.", author: "Anonymous" },
    { text: "The best way to predict the future is to create it.", author: "Alan Kay" },
    { text: "If you don't build your dream, someone else will hire you to help them build theirs.", author: "Dhirubhai Ambani" },
    { text: "Competition is for losers.", author: "Peter Thiel" },
    { text: "Every moment in business happens only once. The next Bill Gates will not build an operating system. The next Larry Page won't make a search engine.", author: "Peter Thiel" },
    { text: "Brilliant thinking is rare, but courage is in even shorter supply than genius.", author: "Peter Thiel" },
    { text: "The most contrarian thing of all is not to oppose the crowd but to think for yourself.", author: "Peter Thiel" },
    { text: "Live life as if there is no luck.", author: "Paul Graham" },
    { text: "It's better to make a few people really happy than to make a lot of people semi-happy.", author: "Paul Graham" },
    { text: "The most dangerous thing is to keep your head down.", author: "Paul Graham" },
    { text: "If you want to do something that will change the world, build a software company. It's easier to make a billion dollars that way than any other way.", author: "Paul Graham" },
    { text: "You don't need a big company to build great things.", author: "Paul Graham" },
    { text: "Being too cautious is the biggest risk of all.", author: "Paul Graham" },
    { text: "The struggle with AI safety is that we're trying to build something smarter than us and make sure it stays on our side.", author: "Dario Amodei" },
    { text: "If you can be the person who creates something genuinely useful, the world tends to figure out how to reward you.", author: "Dario Amodei" },
    { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
    { text: "Failure is an option here. If things are not failing, you are not innovating enough.", author: "Elon Musk" },
    { text: "I think it's possible for ordinary people to choose to be extraordinary.", author: "Elon Musk" },
    { text: "Persistence is very important. You should not give up unless you are forced to give up.", author: "Elon Musk" },
    { text: "Some people don't like change, but you need to embrace change if the alternative is disaster.", author: "Elon Musk" },
    { text: "The first step is to establish that something is possible; then probability will occur.", author: "Elon Musk" },
    { text: "You want to be greedy when others are fearful. You want to be fearful when others are greedy.", author: "Sam Altman" },
    { text: "Great execution is at least ten times more important and a hundred times harder than a good idea.", author: "Sam Altman" },
    { text: "The hard part of running a business is that there are a hundred things that you could be doing, and only five of them matter.", author: "Sam Altman" },
    { text: "Long-term thinking is a competitive advantage because almost no one does it.", author: "Sam Altman" },
    { text: "In a lot of ways, it's not the money that allows you to do new things. It's the growth and the ability to find things that people want and to use your creativity to target those.", author: "Travis Kalanick" },
    { text: "Fear is the disease. Hustle is the antidote.", author: "Travis Kalanick" },

    // Naval Ravikant
    { text: "Seek wealth, not money or status. Wealth is having assets that earn while you sleep.", author: "Naval Ravikant" },
    { text: "You're not going to get rich renting out your time. You must own equity to gain your financial freedom.", author: "Naval Ravikant" },
    { text: "Learn to sell. Learn to build. If you can do both, you will be unstoppable.", author: "Naval Ravikant" },
    { text: "Arm yourself with specific knowledge, accountability, and leverage.", author: "Naval Ravikant" },
    { text: "Specific knowledge is found by pursuing your genuine curiosity and passion rather than whatever is hot right now.", author: "Naval Ravikant" },
    { text: "Building specific knowledge will feel like play to you but will look like work to others.", author: "Naval Ravikant" },
    { text: "The most important skill for getting rich is becoming a perpetual learner.", author: "Naval Ravikant" },
    { text: "Read what you love until you love to read.", author: "Naval Ravikant" },
    { text: "If you can't code, write books and blogs, record videos and podcasts.", author: "Naval Ravikant" },
    { text: "Escape competition through authenticity.", author: "Naval Ravikant" },
    { text: "Play iterated games. All the returns in life come from compound interest.", author: "Naval Ravikant" },
    { text: "Pick business partners with high intelligence, energy, and above all, integrity.", author: "Naval Ravikant" },
    { text: "Don't partner with cynics and pessimists. Their beliefs are self-fulfilling.", author: "Naval Ravikant" },
    { text: "Be patient with results but impatient with actions.", author: "Naval Ravikant" },
    { text: "Judgment requires experience but can be built faster by learning foundational skills.", author: "Naval Ravikant" },
    { text: "There is no skill called business. Avoid business magazines and business classes.", author: "Naval Ravikant" },
    { text: "A fit body, a calm mind, a house full of love. These things cannot be bought—they must be earned.", author: "Naval Ravikant" },
    { text: "Desire is a contract you make with yourself to be unhappy until you get what you want.", author: "Naval Ravikant" },
    { text: "The secret to doing good research is always to be a little underemployed.", author: "Naval Ravikant" },
    { text: "Free education is abundant, all over the internet. It's the desire to learn that's scarce.", author: "Naval Ravikant" },
    { text: "If you're not willing to be misunderstood, you're not going to do anything new or different.", author: "Naval Ravikant" },
    { text: "The modern struggle is to be happy when you already have everything.", author: "Naval Ravikant" },
    { text: "Happiness is a choice and a skill and you can dedicate yourself to learning that skill.", author: "Naval Ravikant" },
    { text: "A calm mind, a fit body, and a house full of love. These things cannot be bought.", author: "Naval Ravikant" },
    { text: "No one can compete with you on being you.", author: "Naval Ravikant" },
    { text: "The best jobs are neither combative nor collaborative. They're creative.", author: "Naval Ravikant" },
    { text: "All the benefits in life come from compound interest — relationships, money, habits.", author: "Naval Ravikant" },
    { text: "You make your own luck if you stay at it long enough.", author: "Naval Ravikant" },
    { text: "Code and media are permissionless leverage. They're the leverage behind the newly rich.", author: "Naval Ravikant" },

    // Bruce Lee
    { text: "Be water, my friend.", author: "Bruce Lee" },
    { text: "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", author: "Bruce Lee" },
    { text: "Absorb what is useful, discard what is useless and add what is specifically your own.", author: "Bruce Lee" },
    { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
    { text: "Knowing is not enough, we must apply. Willing is not enough, we must do.", author: "Bruce Lee" },
    { text: "If you spend too much time thinking about a thing, you'll never get it done.", author: "Bruce Lee" },
    { text: "To hell with circumstances; I create opportunities.", author: "Bruce Lee" },
    { text: "Mistakes are always forgivable, if one has the courage to admit them.", author: "Bruce Lee" },
    { text: "A wise man can learn more from a foolish question than a fool can learn from a wise answer.", author: "Bruce Lee" },
    { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee" },
    { text: "The key to immortality is first living a life worth remembering.", author: "Bruce Lee" },
    { text: "If you always put limits on everything you do, it will spread into your work and into your life.", author: "Bruce Lee" },
    { text: "Adapt what is useful, reject what is useless, and add what is specifically your own.", author: "Bruce Lee" },
    { text: "Don't fear failure. Not failure, but low aim, is the crime.", author: "Bruce Lee" },
    { text: "Long-term consistency trumps short-term intensity.", author: "Bruce Lee" },
    { text: "It's not the daily increase but daily decrease. Hack away at the unessential.", author: "Bruce Lee" },
    { text: "Empty your cup so that it may be filled.", author: "Bruce Lee" },
    { text: "The more we value things, the less we value ourselves.", author: "Bruce Lee" },
    { text: "Real living is living for others.", author: "Bruce Lee" },
    { text: "As you think, so shall you become.", author: "Bruce Lee" },
    { text: "A goal is not always meant to be reached, it often serves simply as something to aim at.", author: "Bruce Lee" },
    { text: "Take things as they are. Punch when you have to punch. Kick when you have to kick.", author: "Bruce Lee" },
    { text: "In the middle of chaos lies opportunity.", author: "Bruce Lee" },
    { text: "The spirit of the individual is determined by his dominating thought habits.", author: "Bruce Lee" },
    { text: "Notice that the stiffest tree is most easily cracked, while the bamboo survives by bending with the wind.", author: "Bruce Lee" },
    { text: "Life itself is your teacher, and you are in a state of constant learning.", author: "Bruce Lee" },
    { text: "Use only that which works, and take it from any place you can find it.", author: "Bruce Lee" },
    { text: "Always be yourself, express yourself, have faith in yourself.", author: "Bruce Lee" },
    { text: "The possession of anything begins in the mind.", author: "Bruce Lee" }
];

// Get a random quote
const quote = quotes[Math.floor(Math.random() * quotes.length)];
document.getElementById('quote').textContent = '"' + quote.text + '"';
document.getElementById('author').textContent = '— ' + quote.author;

// Get blocked site from URL params
const params = new URLSearchParams(window.location.search);
const blockedSite = params.get('site') || 'Unknown site';
document.getElementById('siteName').textContent = blockedSite;
